CROP_CONFIG = {
    "小麦": {
        "grow_time": 3600,
        "sell_price": 10,
        "seed_cost": 5,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "玉米": {
        "grow_time": 7200,
        "sell_price": 20,
        "seed_cost": 10,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "胡萝卜": {
        "grow_time": 5400,
        "sell_price": 15,
        "seed_cost": 8,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "土豆": {
        "grow_time": 4800,
        "sell_price": 12,
        "seed_cost": 6,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "西红柿": {
        "grow_time": 6000,
        "sell_price": 18,
        "seed_cost": 9,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "草莓": {
        "grow_time": 8400,
        "sell_price": 25,
        "seed_cost": 12,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "南瓜": {
        "grow_time": 10800,
        "sell_price": 35,
        "seed_cost": 15,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "向日葵": {
        "grow_time": 14400,
        "sell_price": 50,
        "seed_cost": 20,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "西瓜": {
        "grow_time": 3600 * 6,
        "sell_price": 80,
        "seed_cost": 20,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "甘蔗": {
        "grow_time": 3600 * 6,
        "sell_price": 80,
        "seed_cost": 20,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
}
