CROP_CONFIG = {
    "小麦": {
        "grow_time": 3600,
        "sell_price": 10,
        "seed_cost": 5,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "玉米": {
        "grow_time": 7200,
        "sell_price": 20,
        "seed_cost": 10,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "胡萝卜": {
        "grow_time": 5400,
        "sell_price": 15,
        "seed_cost": 8,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "土豆": {
        "grow_time": 4800,
        "sell_price": 12,
        "seed_cost": 6,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "西红柿": {
        "grow_time": 6000,
        "sell_price": 18,
        "seed_cost": 9,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "草莓": {
        "grow_time": 8400,
        "sell_price": 25,
        "seed_cost": 12,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "南瓜": {
        "grow_time": 10800,
        "sell_price": 35,
        "seed_cost": 15,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "向日葵": {
        "grow_time": 14400,
        "sell_price": 50,
        "seed_cost": 20,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "西瓜": {
        "grow_time": 3600 * 6,
        "sell_price": 80,
        "seed_cost": 20,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "甘蔗": {
        "grow_time": 3600 * 6,
        "sell_price": 80,
        "seed_cost": 20,
        "max_yield": 10,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "玫瑰": {
        "seed_cost": 200,
        "grow_time": 3600 * 3,
        "product_name": "玫瑰",
        "max_yield": 10,
        "sell_price": 50,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "满天星": {
        "seed_cost": 150,
        "grow_time": 1800 * 6,
        "product_name": "满天星",
        "max_yield": 10,
        "sell_price": 40,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "郁金香": {
        "seed_cost": 100,
        "grow_time": 2700 * 3,
        "product_name": "郁金香",
        "max_yield": 10,
        "sell_price": 35,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "百合": {
        "seed_cost": 110,
        "grow_time": 3000 * 3,
        "product_name": "百合",
        "max_yield": 10,
        "sell_price": 38,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "丁香": {
        "seed_cost": 95,
        "grow_time": 2400 * 3,
        "product_name": "丁香",
        "max_yield": 10,
        "sell_price": 33,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "牡丹": {
        "seed_cost": 150,
        "grow_time": 4800 * 3,
        "product_name": "牡丹",
        "max_yield": 10,
        "sell_price": 60,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "兰花": {
        "seed_cost": 130,
        "grow_time": 3300 * 3,
        "product_name": "兰花",
        "max_yield": 10,
        "sell_price": 45,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "康乃馨": {
        "seed_cost": 85,
        "grow_time": 2100 * 3,
        "product_name": "康乃馨",
        "max_yield": 10,
        "sell_price": 32,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "紫罗兰": {
        "seed_cost": 90,
        "grow_time": 2100 * 3,
        "product_name": "紫罗兰",
        "max_yield": 10,
        "sell_price": 34,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
    "芍药": {
        "seed_cost": 100,
        "grow_time": 2100 * 3,
        "product_name": "芍药",
        "max_yield": 10,
        "sell_price": 35,
        "min_owner_yield": 5,
        "max_steal_once": 1,
    },
}
