GARDEN_CONFIG = {
    "玫瑰": {
        "cost": 200,
        "grow_time": 3600 * 3,
        "product_name": "玫瑰",
        "max_yield": 10,
        "sell_price": 50,
    },
    "满天星": {
        "cost": 150,
        "grow_time": 1800 * 6,
        "product_name": "满天星",
        "max_yield": 10,
        "sell_price": 40,
    },
    "郁金香": {
        "cost": 100,
        "grow_time": 2700 * 3,
        "product_name": "郁金香",
        "max_yield": 10,
        "sell_price": 35,
    },
    "百合": {
        "cost": 110,
        "grow_time": 3000 * 3,
        "product_name": "百合",
        "max_yield": 10,
        "sell_price": 38,
    },
    "丁香": {
        "cost": 95,
        "grow_time": 2400 * 3,
        "product_name": "丁香",
        "max_yield": 10,
        "sell_price": 33,
    },
    "牡丹": {
        "cost": 150,
        "grow_time": 4800 * 3,
        "product_name": "牡丹",
        "max_yield": 10,
        "sell_price": 60,
    },
    "兰花": {
        "cost": 130,
        "grow_time": 3300 * 3,
        "product_name": "兰花",
        "max_yield": 10,
        "sell_price": 45,
    },
    "康乃馨": {
        "cost": 85,
        "grow_time": 2100 * 3,
        "product_name": "康乃馨",
        "max_yield": 10,
        "sell_price": 32,
    },
    "紫罗兰": {
        "cost": 90,
        "grow_time": 2100 * 3,
        "product_name": "紫罗兰",
        "max_yield": 10,
        "sell_price": 34,
    },
    "芍药": {
        "cost": 100,
        "grow_time": 2100 * 3,
        "product_name": "芍药",
        "max_yield": 10,
        "sell_price": 35,
    },
}
